name: Deploy Main Website with Blog

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [blog-updated]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Checkout blog repo
      uses: actions/checkout@v3
      with:
        repository: hiepng15/blog
        path: external-blog
        
    - name: Copy blog to main repo
      run: |
        rm -rf blog/
        cp -r external-blog/ blog/
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build website
      run: npm run build
      
    - name: Copy blog to build directory
      run: |
        mkdir -p build/blog
        cp -r blog/* build/blog/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
